#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
usage: bash scripts/prepare_linux_server_env.sh [options]

options:
  --env-file <path>            output env file (default: config/linux_server.env)
  --seed-profile <dir>         seeded Chrome profile root
  --profile-name <name>        Chrome profile name (default: Default)
  --chrome-path <path>         Chrome/Chromium executable path
  --python <path>              python executable path
  --runs-root <dir>            experiment run root
  --logs-root <dir>            launcher log root
  --collect-root <dir>         collected bundle root
  --extract-docs-seed <0|1>    extract docs seed archive when seed dir is missing (default: 1)
EOF
}

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=scripts/_linux_suite_env.sh
source "$SCRIPT_DIR/_linux_suite_env.sh"
REPO_ROOT=$(linux_suite_repo_root)
linux_suite_load_env "$REPO_ROOT"

ENV_FILE=$(linux_suite_env_file "$REPO_ROOT")
SEED_PROFILE_VALUE="${SEED_PROFILE:-$REPO_ROOT/outputs/linux_seed_profile_from_docs/linux_chromium_user_data_seed}"
PROFILE_NAME_VALUE="${PROFILE_NAME:-Default}"
CHROME_PATH_VALUE="${CHROME_PATH:-$HOME/chrome-linux/chrome-linux64/chrome}"
PYTHON_BIN_VALUE="${PYTHON_BIN:-$(command -v python3)}"
RUNS_ROOT_VALUE=$(linux_suite_runs_root "$REPO_ROOT")
LOGS_ROOT_VALUE=$(linux_suite_logs_root "$REPO_ROOT")
COLLECT_ROOT_VALUE=$(linux_suite_collect_root "$REPO_ROOT")
NO_SANDBOX_VALUE="${PDF_BROWSER_NO_SANDBOX:-}"
TMPDIR_VALUE="${TMPDIR:-}"
XDG_RUNTIME_DIR_VALUE="${XDG_RUNTIME_DIR:-}"
EXTRACT_DOCS_SEED=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env-file) ENV_FILE=${2:-}; shift 2 ;;
    --seed-profile) SEED_PROFILE_VALUE=${2:-}; shift 2 ;;
    --profile-name) PROFILE_NAME_VALUE=${2:-}; shift 2 ;;
    --chrome-path) CHROME_PATH_VALUE=${2:-}; shift 2 ;;
    --python) PYTHON_BIN_VALUE=${2:-}; shift 2 ;;
    --runs-root) RUNS_ROOT_VALUE=${2:-}; shift 2 ;;
    --logs-root) LOGS_ROOT_VALUE=${2:-}; shift 2 ;;
    --collect-root) COLLECT_ROOT_VALUE=${2:-}; shift 2 ;;
    --extract-docs-seed) EXTRACT_DOCS_SEED=${2:-1}; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if [[ ! -x "$PYTHON_BIN_VALUE" ]]; then
  echo "python executable not executable: $PYTHON_BIN_VALUE" >&2
  exit 1
fi

if [[ -n "$ENV_FILE" ]]; then
  ENV_FILE=$("$PYTHON_BIN_VALUE" - <<PY
from pathlib import Path
print(Path("$ENV_FILE").resolve())
PY
)
fi

if [[ ! -d "$SEED_PROFILE_VALUE" && "$EXTRACT_DOCS_SEED" == "1" ]]; then
  DOCS_TAR="$REPO_ROOT/docs/linux_chromium_user_data_seed.tar.gz"
  if [[ -f "$DOCS_TAR" ]]; then
    mkdir -p "$(dirname "$SEED_PROFILE_VALUE")"
    tar -xzf "$DOCS_TAR" -C "$(dirname "$SEED_PROFILE_VALUE")"
  fi
fi

if [[ ! -d "$SEED_PROFILE_VALUE" ]]; then
  echo "seed profile directory not found: $SEED_PROFILE_VALUE" >&2
  exit 1
fi
if [[ ! -x "$CHROME_PATH_VALUE" ]]; then
  echo "chrome executable not executable: $CHROME_PATH_VALUE" >&2
  exit 1
fi

mkdir -p "$(dirname "$ENV_FILE")" "$RUNS_ROOT_VALUE" "$LOGS_ROOT_VALUE" "$COLLECT_ROOT_VALUE"

{
  echo "# Generated by scripts/prepare_linux_server_env.sh"
  echo "# Machine-local Linux server settings. Do not commit."
  printf 'SEED_PROFILE=%q\n' "$SEED_PROFILE_VALUE"
  printf 'PROFILE_NAME=%q\n' "$PROFILE_NAME_VALUE"
  printf 'CHROME_PATH=%q\n' "$CHROME_PATH_VALUE"
  printf 'PYTHON_BIN=%q\n' "$PYTHON_BIN_VALUE"
  printf 'RUNS_ROOT=%q\n' "$RUNS_ROOT_VALUE"
  printf 'LOGS_ROOT=%q\n' "$LOGS_ROOT_VALUE"
  printf 'COLLECT_ROOT=%q\n' "$COLLECT_ROOT_VALUE"
  printf 'PDF_BROWSER_NO_SANDBOX=%q\n' "$NO_SANDBOX_VALUE"
  printf 'TMPDIR=%q\n' "$TMPDIR_VALUE"
  printf 'XDG_RUNTIME_DIR=%q\n' "$XDG_RUNTIME_DIR_VALUE"
} >"$ENV_FILE"

SEED_CHECK_JSON=$("$PYTHON_BIN_VALUE" "$REPO_ROOT/scripts/check_linux_seed_profile.py" \
  --profile-root "$SEED_PROFILE_VALUE" \
  --profile-name "$PROFILE_NAME_VALUE")
CHROME_VERSION=$("$CHROME_PATH_VALUE" --version 2>/dev/null || true)

echo "env_file=$ENV_FILE"
echo "seed_profile=$SEED_PROFILE_VALUE"
echo "profile_name=$PROFILE_NAME_VALUE"
echo "chrome_path=$CHROME_PATH_VALUE"
echo "python_bin=$PYTHON_BIN_VALUE"
echo "runs_root=$RUNS_ROOT_VALUE"
echo "logs_root=$LOGS_ROOT_VALUE"
echo "collect_root=$COLLECT_ROOT_VALUE"
echo "chrome_version=$CHROME_VERSION"
echo "seed_profile_check=$SEED_CHECK_JSON"
